import type { Gem, RepairOrder } from "./types";

const gem = (
  id: string,
  kind: string,
  shape: string,
  carat: number,
  sizeMm: number,
  color: string,
  clarity: string,
  cut: string,
  status: Gem["status"] = "在库",
  assignedOrderId: string | null = null,
  note?: string
): Gem => ({ id, kind, shape, carat, sizeMm, color, clarity, cut, status, assignedOrderId, note });

/** 返修订单：每单若干镶嵌位，均带拆下的旧宝石 */
export const seedOrders: RepairOrder[] = [
  {
    id: "RP-1024",
    customer: "陈女士",
    ringName: "蓝宝石钻戒",
    slots: [
      {
        id: "RP-1024-S1",
        label: "主石位",
        angle: -90,
        targetSizeMm: 6.0,
        toleranceMm: 0.3,
        originalGem: gem("ST-2048", "蓝宝石", "椭圆", 1.2, 6.0, "皇家蓝", "VVS1", "优"),
        defect: "台面划痕",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1024-S2",
        label: "围石A-1",
        angle: 30,
        targetSizeMm: 2.5,
        toleranceMm: 0.15,
        originalGem: gem("ST-2061", "钻石", "圆形", 0.08, 2.5, "F", "VS1", "优"),
        defect: "脱落找回",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1024-S3",
        label: "围石A-2",
        angle: 90,
        targetSizeMm: 2.5,
        toleranceMm: 0.15,
        originalGem: gem("ST-2055", "钻石", "圆形", 0.08, 2.5, "F", "VS1", "良"),
        defect: "腰部崩口",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1024-S4",
        label: "围石A-3",
        angle: 150,
        targetSizeMm: 2.5,
        toleranceMm: 0.15,
        originalGem: gem("ST-2057", "钻石", "圆形", 0.08, 2.5, "G", "VS2", "良"),
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
    ],
  },
  {
    id: "RP-1025",
    customer: "王先生",
    ringName: "钻石婚戒",
    slots: [
      {
        id: "RP-1025-S1",
        label: "主石位",
        angle: -90,
        targetSizeMm: 5.8,
        toleranceMm: 0.25,
        originalGem: gem("ST-2101", "钻石", "圆形", 0.75, 5.8, "E", "VVS2", "优"),
        defect: "底尖磨损",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1025-S2",
        label: "副石左",
        angle: -30,
        targetSizeMm: 3.4,
        toleranceMm: 0.2,
        originalGem: gem("ST-2102", "钻石", "圆形", 0.15, 3.4, "F", "VS1", "优"),
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1025-S3",
        label: "副石右",
        angle: -150,
        targetSizeMm: 3.4,
        toleranceMm: 0.2,
        originalGem: gem("ST-2103", "钻石", "圆形", 0.15, 3.4, "F", "VS1", "优"),
        defect: "丢失补配",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
    ],
  },
  {
    id: "RP-1026",
    customer: "林女士",
    ringName: "祖母绿戒指",
    slots: [
      {
        id: "RP-1026-S1",
        label: "主石位",
        angle: -90,
        targetSizeMm: 6.5,
        toleranceMm: 0.3,
        originalGem: gem("ST-2099", "祖母绿", "祖母绿切", 0.9, 6.5, "艳绿", "VS2", "优"),
        defect: "内含物明显",
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1026-S2",
        label: "围石B-1",
        angle: 35,
        targetSizeMm: 2.3,
        toleranceMm: 0.15,
        originalGem: gem("ST-2110", "钻石", "圆形", 0.06, 2.3, "G", "VS2", "良"),
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
      {
        id: "RP-1026-S3",
        label: "围石B-2",
        angle: 145,
        targetSizeMm: 2.3,
        toleranceMm: 0.15,
        originalGem: gem("ST-2111", "钻石", "圆形", 0.06, 2.3, "G", "VS2", "良"),
        disposition: null,
        replacementGemId: null,
        state: "待拆",
      },
    ],
  },
];

/** 替石库：含已分给其他订单的占用石 */
export const seedGems: Gem[] = [
  gem("ST-301", "蓝宝石", "椭圆", 1.15, 6.1, "皇家蓝", "VVS1", "优"),
  gem("ST-302", "蓝宝石", "椭圆", 1.3, 6.5, "矢车菊", "VS1", "优"),
  gem("ST-303", "蓝宝石", "椭圆", 1.1, 6.0, "中蓝", "VVS1", "良"),
  gem("ST-304", "蓝宝石", "椭圆", 1.18, 6.2, "皇家蓝", "VS2", "优"),
  gem("ST-310", "钻石", "圆形", 0.08, 2.5, "F", "VS1", "优"),
  gem("ST-311", "钻石", "圆形", 0.08, 2.5, "E", "VVS2", "优"),
  gem("ST-312", "钻石", "圆形", 0.09, 2.7, "F", "VS1", "良"),
  gem("ST-313", "钻石", "圆形", 0.08, 2.5, "H", "SI1", "良", "在库", null, "特价石"),
  gem("ST-314", "钻石", "圆形", 0.06, 2.3, "G", "VS2", "良"),
  gem("ST-315", "钻石", "圆形", 0.06, 2.4, "F", "VS1", "优"),
  gem("ST-320", "钻石", "圆形", 0.72, 5.9, "D", "VVS1", "优", "已分配", "RP-1025"),
  gem("ST-321", "钻石", "圆形", 0.15, 3.4, "F", "VS1", "优", "已分配", "RP-1025"),
  gem("ST-322", "钻石", "圆形", 0.75, 5.8, "F", "VVS2", "优"),
  gem("ST-323", "钻石", "圆形", 0.74, 5.7, "E", "VVS2", "优"),
  gem("ST-324", "钻石", "圆形", 0.15, 3.4, "F", "VS1", "优"),
  gem("ST-325", "钻石", "圆形", 0.16, 3.5, "G", "VS2", "良"),
  gem("ST-330", "祖母绿", "祖母绿切", 0.95, 6.4, "沃顿绿", "VS1", "优", "已分配", "RP-1026"),
  gem("ST-331", "祖母绿", "祖母绿切", 0.92, 6.6, "艳绿", "VS2", "优"),
  gem("ST-332", "祖母绿", "祖母绿切", 0.88, 6.3, "正绿", "VS1", "良"),
  gem("ST-340", "红宝石", "椭圆", 0.6, 5.0, "鸽血红", "VVS2", "优"),
];
